# Generated by Django 5.0.6 on 2024-07-12 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Dodatečné poznámky')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Název')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('founded', models.DateField(blank=True, null=True, verbose_name='Datum založení')),
            ],
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='GPU')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=164, null=True, verbose_name='HDD')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operační systém')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_platform', models.CharField(choices=[('PC', 'PC'), ('PS', 'Playstation'), ('XBOX', 'Xbox')], max_length=10, verbose_name='Platforma')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Název')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('founded', models.DateField(blank=True, null=True, verbose_name='Datum založení')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='RAM')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Název')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Datum vydání')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Množství')),
                ('developer', models.ManyToManyField(blank=True, related_name='developer_of_game', to='viewer.developer', verbose_name='Vývojář')),
                ('min_additional_notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_game_notes', to='viewer.additionalnotes', verbose_name='Dodatečné poznámky')),
                ('min_configuration_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_cpu', to='viewer.cpu', verbose_name='CPU (Minimální')),
                ('recommended_configuration_additional_notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_game_notes', to='viewer.additionalnotes', verbose_name='Dodatečné poznámky')),
                ('recommended_configuration_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_cpu', to='viewer.cpu', verbose_name='CPU (Dporučené)')),
                ('game_mode', models.ManyToManyField(blank=True, related_name='mode_of_game', to='viewer.gamemode', verbose_name='Herní mód')),
                ('genres', models.ManyToManyField(blank=True, related_name='genres_of_game', to='viewer.genre', verbose_name='Žánr')),
                ('min_configuration_gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_gpu', to='viewer.gpu', verbose_name='GPU (Minimální')),
                ('recommended_configuration_gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_gpu', to='viewer.gpu', verbose_name='GPU (Dporučené)')),
                ('min_configuration_hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_hdd', to='viewer.hdd', verbose_name='HDD (Minimální)')),
                ('recommended_configuration_hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_hdd', to='viewer.hdd', verbose_name='HDD (Doporučené)')),
                ('min_configuration_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_os', to='viewer.os', verbose_name='Minimální operační systém')),
                ('recommended_configuration_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_os', to='viewer.os', verbose_name='Doporučený operační systém')),
                ('platform', models.ManyToManyField(blank=True, related_name='platform_games', to='viewer.platform', verbose_name='Platforma')),
                ('publisher', models.ManyToManyField(blank=True, related_name='publisher_of_game', to='viewer.publisher', verbose_name='Vydavatel')),
                ('min_configuration_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_ram', to='viewer.ram', verbose_name='RAM (Minimální)')),
                ('recommended_configuration_ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_ram', to='viewer.ram', verbose_name='RAM (Doporučené)')),
            ],
        ),
        migrations.CreateModel(
            name='DLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Název')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Datum vydání')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlcs', to='viewer.game')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Komentář')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Změněno')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.game')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_items', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='viewer.game')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Množství')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Datum nákupu')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='viewer.game', verbose_name='Hra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Zákazník')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Hodnocení')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
