# Generated by Django 5.0.6 on 2024-07-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_images/')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='viewer.game')),
            ],
        ),
    ]
