# Generated by Django 5.0.6 on 2024-07-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_gameimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameimage',
            old_name='Game',
            new_name='game',
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(upload_to='viewer/static/game_images/'),
        ),
    ]
