# Generated by Django 5.0.6 on 2024-08-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_gamevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(blank=True, related_name='games_by_developer', to='viewer.developer', verbose_name='Vývojář'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_mode',
            field=models.ManyToManyField(blank=True, related_name='games_by_mode', to='viewer.gamemode', verbose_name='Herní mód'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games_by_genre', to='viewer.genre', verbose_name='Žánr'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(blank=True, related_name='games_by_developer', to='viewer.platform', verbose_name='Platforma'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ManyToManyField(blank=True, related_name='games_by_publisher', to='viewer.publisher', verbose_name='Vydavatel'),
        ),
    ]
