# Generated by Django 5.0.6 on 2024-08-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_cart_created_at_purchase_is_paid_purchase_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='game',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='game',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='is_paid',
        ),
    ]
