# Generated by Django 5.0.6 on 2024-05-18 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulice')),
                ('house_number', models.IntegerField(blank=True, null=True, verbose_name='Číslo domu')),
                ('city', models.CharField(blank=True, max_length=132, null=True, verbose_name='Město')),
                ('country', models.CharField(blank=True, max_length=132, null=True, verbose_name='Země')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='PSČ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users_image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.profile')),
            ],
        ),
    ]
